import { AiFillStar } from "react-icons/ai";

export const data1 = [
    {
      id:1,
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      title: "Nike Air Monarch IV",
      text: "Durable leather on top provides solid support, while lightweight foam teams up with Nike Air cushioning to keep you moving in comfort.",
      reviews: "(123 reviews)",
      prevPrice: "1400",
      newPrice: 120,
      company: "nike",
      color: "white",
      category: "sneakers",
      type:"men",
      qty:1,
      color: "from-blue-600 to-blue-500",
      shadow: "shadow-lg shadow-blue-500",
    },
    {
      id:2,
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      text: "The Nike Air VaporMax Plus looks to the past to propel you into the future.",
      reviews: "(123 reviews)",
      prevPrice: "1400",
      newPrice: 345,
      company: "nike",
      color: "red",
      category: "sneakers",
      type:"men",
      qty:1,
      color: "from-red-500 to-rose-500",
      shadow: "shadow-lg shadow-rose-500",
      
    },
    {
      id:3,
      img: "https://media.istockphoto.com/id/477850598/photo/sport-shoes.jpg?s=612x612&w=0&k=20&c=Pk3XBtR7Q6twhW96ntjyAH1OpxsuCJJfVB5x2nMIh0k=",
      title: "Downshifter 12 Running Shoe",
      text: "Take those first steps on you running journey in the Nike Downshifter 12. It's got a supportive fit and a stable ride, with a lightweight feel that easily transitions from your workout to hanging out.",
      reviews: "(123 reviews)",
      prevPrice: "1400",
      newPrice: 234,
      company: "nike",
      color: "red",
      category: "sneakers",
      type:"women",
      qty:1,
      color: "from-violet-500 to-indigo-500",
      shadow: "shadow-lg shadow-violet-500",
    },
    {
      id:4,
      title: "Jordan Air 1 Retro High OG Men's",
      text: "Peter Moore's genius design from '85 always delivers all these decades later. This season it returns with an OG High 'Washed Black' setup, bringing classic colours and suede detailing to the mix, all showcased on a piece of Michael Jordan history.",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ6cpCcQr0TMVxEjid_Gt0VtyHimC4ZbKEBGvCLMH4ZFRKpKedA5qperHXCg3ZAPIohlC2Ey45t_u1GECMymyM6TFoMKBKT4zwK_DBBs7aNB1Ij1IpIq7CgrwQ",
      time: "25 Days",
      prevPrice: "14000",
      newPrice: 1540,
      like: "3/5",
      by: "Jared Ebanks",
      btn: "Read More",
      company:"nike",
      category:"sneakers",
      type:"men",
      qty:1,
    },
    {
      id:5,
      title: "Nike Air Force Orange Color",
      text: "From lace toggles to city-inspired makeovers, the Nike Air Force 1 has delivered a number of unique modifications. Here though, the brand is taking things down quite a few notches, opting for a simple colorway helmed primarily by black and Laser Orange.",
      img: "https://sneakernews.com/wp-content/uploads/2022/09/Nike-Air-Force-1-Black-Yellow-FB7162-081-8.jpg?w=540&h=380&crop=1",
      url: "https://sneakernews.com/2022/09/09/nike-air-force-1-black-laser-orange-fb7162-081/",
      prevPrice: "1400",
      newPrice: 456,
      time: "6 Days",
      like: "4/5",
      by: "Micael Le",
      btn: "Read More",
      company: "nike",
      type:"men",
      category:"formal",
      qty:1,
    },
    {
      id:6,
      title: "Adidas Canvas",
      prevPrice: "1400",
      newPrice: 765,
      text: "The world of Sanrio is vast and replete with many an iconic character. Few among the family, though, rival the immense influence of Hello Kitty, who’s played mascot for everything from Pringles merchandise to sneaker collaborations.",
      img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/15f901c90a9549d29104aae700d27efb_9366/SUPERSTAR_SHOES_Black_EG4959_01_standard.jpg",
      url: "https://sneakernews.com/2022/09/08/hello-kitty-adidas-originals-gw7166-gw7167-gw7168/",
      time: "5 Days",
      like: "4/5",
      by: "Micael Le",
      btn: "Read More",
      company:"adidas",
      type:"women",
      category:"casual",
      qty:1,
    },
    {
      id:7,
      title: "Air Force 1 Low Expands",
      prevPrice: "1400",
      newPrice: 890,
      text: "The nighttime aesthetic seen here is applied to the tumbled black leather panels of the upper and perforated mesh construction of the tongue while Royal trim and forefoot Swooshes provide additional intrigue to the darkened palette.",
      img: "https://sneakernews.com/wp-content/uploads/2022/09/nike-air-force-1-low-worldwide-black-royal-fb1840-001-lead.jpg?w=540&h=380&crop=1",
      url: "https://sneakernews.com/2022/09/08/nike-air-force-1-low-worldwide-black-royal-fb1840-001/",
      time: "5 Days",
      like: "4/5",
      by: "Micael Le",
      btn: "Read More",
      type:"women",
      company:"nike",
      qty:1,
    },
    {
      id:8,
      title: "PRIMUS LITE KNIT MENS",
      text: "Jordan Brands signature model for the past few years, Jayson Tatum will be dawning the Air Jordan 37 this season before attaining potentially his first signature sneaker with Jumpman, which he rumored to be in the works recently via his Twitter.",
      prevPrice: "1400",
      newPrice: 546,
      img: "https://www.vivobarefoot.com/media/catalog/product/3/0/309304-01_side_2.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=709&width=1260",
      like: "3/5",
      time: "11 Mins",
      by: "Jared Ebanks",
      btn: "Read More",
      type:"men",
      company:"nike",
      qty:1,
    },
    {
      id:9,
      title: "Bro’s Nike Zoom Freak 4",
      text: "Arriving right time for the Fall, this upcoming take on the Zoom Freak 4 seemingly draws inspiration from Thanksgiving. Orange and brown, two staples of the holiday, are used throughout the upper, dressing the parts not bathed in shades of grey.",
      img: "https://sneakernews.com/wp-content/uploads/2022/09/nike-zoom-freak-4-ironstone-orange-trance-cobblestone-sail-dj6149-003-2.jpg?w=540&h=380&crop=1",
      time: "41 Mins",
      like: "5/5",
      by: "Michael Le",
      btn: "Read More",
      type:"Women",
      prevPrice: "1400",
      newPrice: 564,
      company:"nike",
      qty:1
    },
    {
      id:10,
      title: "Synthetic Leather ",
      text: "Arriving right time for the Fall, this upcoming take on the Zoom Freak 4 seemingly draws inspiration from Thanksgiving. Orange and brown, two staples of the holiday, are used throughout the upper, dressing the parts not bathed in shades of grey.",
      img: "https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/q/4/a/4-mrj1992-4-aadi-white-black-yellow-original-imagg3kryyszam65.jpeg?q=70",
      time: "41 Mins",
      like: "5/5",
      by: "Michael Le",
      btn: "Read More",
      type:"Women",
      prevPrice: "140",
      newPrice: 54,
      company:"nike",
      qty:1
    },
    {
      id:11,
      title: "Adidas Men Ultimashow Running",
      text: "Arriving right time for the Fall, this upcoming take on the Zoom Freak 4 seemingly draws inspiration from Thanksgiving. Orange and brown, two staples of the holiday, are used throughout the upper, dressing the parts not bathed in shades of grey.",
      img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ1aYK-rynSj9wPxYWRZCfLa4ckUe0d29SNSlLNHOJGflo8GbzCQWl1fprcaFGVLx-W_JFXpwX0288xKlo2b8jtSasUVDdOESkmIuo_JaNqlxRVKG_jRdAVcQ",
      time: "41 Mins",
      like: "5/5",
      by: "Michael Le",
      btn: "Read More",
      type:"Women",
      prevPrice: "1490",
      newPrice: 504,
      company:"adidas",
      qty:1
    },
    {
      id:12,
      title: "Mens Ultimate Ease Walking Shoe ",
      text: "Arriving right time for the Fall, this upcoming take on the Zoom Freak 4 seemingly draws inspiration from Thanksgiving. Orange and brown, two staples of the holiday, are used throughout the upper, dressing the parts not bathed in shades of grey.",
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRc430J7GN7jOOVDnj5Lg5IHnhumMqW9fjlRbUJhWqO6vLWa59omlHfIOo8QoQgeU6tkMO9Di8O8XehKntWNLHd1mmQDj8W3hXN93uxy9YCQR6B7ymKYohhcA",
      time: "41 Mins",
      like: "5/5",
      by: "Michael Le",
      btn: "Read More",
      type:"Women",
      prevPrice: "500",
      newPrice: 299,
      company:"nike",
      qty:1
    },
]
